language: python
python:
  - 3.3
  - 3.4
  - 3.5
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gettext intltool
script:
  - python setup.py clean
  - python setup.py install --prefix=/tmp/usr
notifications:
  on_success: change
  on_failure: change
