language: python
python:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gettext gir1.2-gtk-3.0 intltool python3-gi xvfb
script:
  - xvfb-run py.test nfoview
  - python setup.py clean
  - python setup.py install --prefix=/tmp/usr
