dist: bionic
before_install:
  - sudo apt-get update
  - >
    sudo apt-get install -y
    flake8
    gettext
    gir1.2-gtk-3.0
    python3
    python3-dev
    python3-gi
    python3-pytest
    xvfb
script:
  - flake8 .
  - xvfb-run py.test-3 nfoview
  - python3 setup.py install --prefix=/tmp/local
  - python3 setup.py install --root=/tmp/pkg
  - python3 setup.py clean
